# Auto-generated from .repo.toml by 'just repo_toml_generate'
# DO NOT EDIT THIS FILE MANUALLY - regenerate with: just repo_toml_generate

# About section
REPO_DESCRIPTION="Automate starting over in Pixel Traffic: Circle Rush"
REPO_LICENSE=""
REPO_TOPICS="circle-rush,sikuli,sikulix"

# URLs section
REPO_GIT_SSH="git@github.com:chicks-net/pixel_traffic_sikuli.git"
REPO_WEB_URL="https://github.com/chicks-net/pixel_traffic_sikuli"

# Derived values
REPO_ORG_NAME="chicks-net"
REPO_REPO_NAME="pixel_traffic_sikuli"

# Feature flags (strings: "true" or "false")
FLAG_CLAUDE="false"
FLAG_CLAUDE_REVIEW="false"
FLAG_COPILOT_REVIEW="true"
FLAG_STANDARD_RELEASE="true"

# Topics as array (for iteration)
REPO_TOPICS_ARRAY=(
    "circle-rush"
    "sikuli"
    "sikulix"
)
